# Generated by Django 3.2.8 on 2022-02-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pensioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pay', models.IntegerField(null=True)),
                ('qs', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=200, null=True)),
                ('comm_rate', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('dob', models.CharField(max_length=20, null=True)),
                ('doa', models.CharField(max_length=20, null=True)),
                ('dor', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Increase',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pms.pensioner')),
                ('inc2001', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2002', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2003', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2004', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2005', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2006', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2007', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2008', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2009', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2010', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2011', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2012', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2013', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2014', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2015', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2016', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2017', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2018', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2019', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('inc2021', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
        ),
    ]
