# Generated by Django 3.2.8 on 2021-10-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pensioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pay', models.IntegerField()),
                ('qs', models.IntegerField()),
                ('gp', models.IntegerField()),
                ('np', models.IntegerField()),
            ],
        ),
    ]
