# Generated by Django 3.2.8 on 2022-01-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensioner',
            name='gp',
        ),
        migrations.RemoveField(
            model_name='pensioner',
            name='np',
        ),
    ]
