# Generated by Django 3.2.8 on 2022-01-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_auto_20220128_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensioner',
            name='doa',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='dor',
            field=models.DateField(null=True),
        ),
    ]
