# Generated by Django 3.2.8 on 2022-03-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_auto_20220303_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensioner',
            name='comm_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pensioner',
            name='gp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pensioner',
            name='np',
            field=models.FloatField(null=True),
        ),
    ]
