# Generated by Django 3.2.8 on 2022-02-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_auto_20220131_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensioner',
            name='age',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
