# Generated by Django 3.2.8 on 2022-03-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_auto_20220303_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Increase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
