# Generated by Django 3.2.8 on 2022-02-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_pensioner_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensioner',
            name='comm_rate',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
