# Generated by Django 3.2.8 on 2022-03-08 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_increase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionIncreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc11', models.FloatField()),
                ('inc15', models.FloatField()),
                ('inc16', models.FloatField()),
                ('inc17', models.FloatField()),
                ('inc18', models.FloatField()),
                ('inc19', models.FloatField()),
                ('inc21', models.FloatField()),
                ('pensioner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pms.pensioner')),
            ],
        ),
    ]
