# Generated by Django 3.2.8 on 2022-02-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_pensioner_comm_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensioner',
            name='pay',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pensioner',
            name='qs',
            field=models.IntegerField(null=True),
        ),
    ]
