# Generated by Django 3.2.8 on 2022-03-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_pensionincreas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionincreas',
            name='pensioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pms.pensioner', unique=True),
        ),
    ]
