# Generated by Django 3.2.8 on 2022-02-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_auto_20220211_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensioner',
            name='qs',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
