# Generated by Django 4.0.3 on 2022-03-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0010_pensioner_inc11_pensioner_inc15_pensioner_inc16_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensioner',
            name='inc03',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='inc04',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='inc05',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='inc06',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='inc07',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='inc08',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='inc09',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='inc10',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='ma2010',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='ma2015',
            field=models.FloatField(null=True),
        ),
    ]
