# Generated by Django 4.0.3 on 2022-03-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0011_pensioner_inc03_pensioner_inc04_pensioner_inc05_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensioner',
            name='inc12',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='inc13',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='inc14',
            field=models.FloatField(null=True),
        ),
    ]
