# Generated by Django 4.0.3 on 2022-03-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_pensioner_inc12_pensioner_inc13_pensioner_inc14'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensioner',
            name='tp',
            field=models.FloatField(null=True),
        ),
    ]
