# Generated by Django 4.0.3 on 2022-04-14 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0013_pensioner_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensioner',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='bps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='cnic',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='fname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='opay',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='ppay',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='ppo',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='qpay',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='spay',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='ui',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=10)),
                ('bb', models.CharField(max_length=20)),
                ('acctno', models.CharField(max_length=20)),
                ('pensioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.pensioner')),
            ],
        ),
    ]
