# Generated by Django 4.0.3 on 2022-06-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0015_pensioner_inc22_pensioner_rest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensioner',
            name='restd',
            field=models.DateField(null=True),
        ),
    ]
