# Generated by Django 4.0.3 on 2022-06-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0016_pensioner_restd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensioner',
            name='restd',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
