# Generated by Django 4.0.3 on 2022-06-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0018_delete_increase_pensioner_cat_pensioner_dobf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pensioner',
            old_name='rest_amount',
            new_name='cp',
        ),
        migrations.AddField(
            model_name='pensioner',
            name='dod',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='rbs',
            field=models.IntegerField(null=True),
        ),
    ]
